---
title: 'Mixture cure models using the BRCA-TCGA dataset'
output: html_document
fontsize: 12pt
published: false
status: no_process
mathjax: true
---

```{r,echo=F,message=FALSE,warning=FALSE,results='hide'}
# Call in the CRAN packages
ll <- c('tidyverse','magrittr','forcats','stringr','cowplot','scales','reshape2','broom','ggrepel',
        'survival','smcure','GGally')
sapply(ll,function(l) require(l,character.only = T))
# Load the data and attach
# load('extra_batch_effects/rmd_data_batch.Rdata')
# attach(rmd.list)
# # Assign the names...
# for (k in 1:length(rmd.list)) {
#   assign(names(rmd.list)[k],rmd.list[[names(rmd.list)[k]]])
# }
```

Checking the robustness of modelling assumptions in time-to-event models, i.e. [survival analysis](https://en.wikipedia.org/wiki/Survival_analysis) in a clinical setting, can be done through a range of residual-based tests [Cox-Snell, Martingale, Deviance, and Schoenfeld](http://www.math.ucsd.edu/~rxu/math284/slect9.pdf). The advantages of each of these approaches has been studied in detail for classical Cox regression models, where :



However, when  for modelling situations in which a fraction of patients may "escape" the disease state, a 

Traditional The goal of this post to review a [new method](https://www.ncbi.nlm.nih.gov/pubmed/27598783) from Peng & Taylor (2016) published in *Biometrics*   for checking mixtu 

The goal of this post is two-fold:

1. Explore the biological data found in TCGA-BRCA dataset across a range of platforms
2. Use the mixture model diagnostics from Peng and Talyor (2016), which will now be donoted PT16.

http://www.cbioportal.org/study?id=brca_tcga#summary

